version: "3"

services:
  code:
    container_name: ETL
    restart: on-failure
    build:
      context: ./code
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_started
#    volumes:
#      - end_to_end:/data
    networks:
      - fastapi_postgres


  fastapi_app:
    container_name: fastapi
    restart: on-failure
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      code:
        condition: service_completed_successfully
    networks:
      - fastapi_postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    env_file:
      - .env
#    volumes:
#      - end_to_end:/var/lib/postgresql/data
    networks:
      - fastapi_postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - fastapi_postgres
    depends_on:
      postgres:
        condition: service_started

networks:
  fastapi_postgres:

#volumes:
#  end_to_end: