version: "3"

services:
  fastapi_app:
    container_name: fastapi
    restart: on-failure
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    networks:
      - fastapi_postgres

  postgres:
    image: postgres
    container_name: my_postgres
    restart: on-failure
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - fastapi_postgres
    depends_on:
      postgres:
        condition: service_started

networks:
  fastapi_postgres:

volumes:
  postgres_data:
